[book]
authors = ["Muhammad"]
language = "en"
description = "This is a comprehensive guide created to help with AWS SAA Exam"
multilingual = false
src = "src"
google-analytics = "UA-102325928-1"
git-repository-url = "https://github.com/mraza007/aws-notes"
title = "Everything you need to know for SAA Exam"
